package it.polimi.ingsw.client.gui.Controllers;

import it.polimi.ingsw.client.Cards;
import it.polimi.ingsw.client.gui.GUI;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;
import javafx.scene.control.ChoiceDialog;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.Modality;

import java.util.*;

public class BoardController implements GUIController{
    private GUI gui;

    @FXML private ImageView dev0, dev1, dev2;
    @FXML private ImageView leader0, leader1;
    @FXML private Label sp_leader0, sp_leader1;
    @FXML private Label slot0, slot1, slot2;

    //Tutti i metodi seguenti sono in risposta alla pressione di un tasto. Recuperano controller corrispondente alla scena
    //da GUI e chiamano su di essi il metodo appropriato

    /**
     * Method called when a user clicks on the market button in board.fxml. It checks if the user can do it (his turn and
     * !doneMandatory), then calls the market() method on the MarketController
     * @param event event generated by the press of the button
     */
    public void market(ActionEvent event){
        if (!gui.getModelView().isActiveTurn()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("It is not your turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        if (gui.getModelView().isDoneMandatory()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("You already did a mandatory action in this turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        MarketController controller= (MarketController) gui.getControllerFromName("market.fxml");
        controller.market();
    }

    /**
     * Method called when a user clicks on the buy button in board.fxml. It checks if the user can do it (his turn and
     * !doneMandatory), then calls the buy() method on the BuyController
     * @param event event generated by the press of the button
     */
    public void buy(ActionEvent event){
        if (!gui.getModelView().isActiveTurn()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("It is not your turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        if (gui.getModelView().isDoneMandatory()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("You already did a mandatory action in this turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        BuyController controller= (BuyController) gui.getControllerFromName("buy.fxml");
        controller.buy();
    }

    /**
     * Method called when a user clicks on the produce button in board.fxml. It checks if the user can do it (his turn and
     * !doneMandatory), then calls the produce() method on the ProduceController
     * @param event event generated by the press of the button
     */
    public void produce(ActionEvent event){
        if (!gui.getModelView().isActiveTurn()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("It is not your turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        if (gui.getModelView().isDoneMandatory()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("You already did a mandatory action in this turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        ProduceController controller= (ProduceController) gui.getControllerFromName("produce.fxml");
        controller.produce();
    }

    /**
     * Method called when a user clicks on the activate button in board.fxml. It checks if the user can do it (his turn),
     * then shows a custom Alert asking the user to pick the leader he wants to activate
     * @param event event generated by the press of the button
     */
    public void activate(ActionEvent event){
        //Tramite Alert.CONFIRMATION chiedono indice leader da attivare, poi invia pack
        if (!gui.getModelView().isActiveTurn()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("It is not your turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        Map<String, String> pack= new HashMap<>();
        pack.put("action", "activate");
        pack.put("player", gui.getModelView().getName());

        Alert activate= new Alert(Alert.AlertType.CONFIRMATION);
        activate.setHeaderText("Choose leader");
        activate.setContentText("Choose the leader you want to activate");
        ButtonType one=new ButtonType("Leader 0");
        ButtonType two= new ButtonType("Leader 1");
        activate.getButtonTypes().setAll(one, two);
        activate.initModality(Modality.APPLICATION_MODAL);
        Optional<ButtonType> result=activate.showAndWait();

        if (result.isPresent() && result.get()==one) {
            pack.put("pos", "0");
        }
        else if (result.isPresent() && result.get()==two) {
            pack.put("pos", "1");
        }
        else return;

        Alert confirm= new Alert(Alert.AlertType.CONFIRMATION);
        confirm.setHeaderText("Choose leader");
        confirm.setContentText("You chose to activate leader in position "+pack.get("pos")+". Is it ok?");
        confirm.initModality(Modality.APPLICATION_MODAL);
        result=confirm.showAndWait();
        if (result.isPresent() && result.get()==ButtonType.OK){
            gui.getModelView().setActiveTurn(false);
            gui.getListeners().fireUpdates(pack.get("action"), pack);
        }
    }

    /**
     * Method called when a user clicks on the discard button in board.fxml. It checks if the user can do it (his turn),
     * then shows a custom Alert asking the user to pick the leader he wants to discard
     * @param event event generated by the press of the button
     */
    public void discard(ActionEvent event){
        //Tramite Alert.CONFIRMATION chiedono indice leader da scartare, poi invia pack
        if (!gui.getModelView().isActiveTurn()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("It is not your turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        Map<String, String> pack= new HashMap<>();
        pack.put("action", "discard");
        pack.put("player", gui.getModelView().getName());

        Alert discard= new Alert(Alert.AlertType.CONFIRMATION);
        discard.setHeaderText("Choose leader");
        discard.setContentText("Choose the leader you want to discard");
        ButtonType one=new ButtonType("Leader 0");
        ButtonType two= new ButtonType("Leader 1");
        discard.getButtonTypes().setAll(one, two);
        discard.initModality(Modality.APPLICATION_MODAL);
        Optional<ButtonType> result=discard.showAndWait();

        if (result.isPresent() && result.get()==one) {
            pack.put("pos", "0");
        }
        else if (result.isPresent() && result.get()==two) {
            pack.put("pos", "1");
        }
        else return;

        Alert confirm= new Alert(Alert.AlertType.CONFIRMATION);
        confirm.setHeaderText("Choose leader");
        confirm.setContentText("You chose to discard leader in position "+pack.get("pos")+". is it ok?");
        confirm.initModality(Modality.APPLICATION_MODAL);
        result=confirm.showAndWait();
        if (result.isPresent() && result.get()==ButtonType.OK){
            gui.getModelView().setActiveTurn(false);
            gui.getListeners().fireUpdates(pack.get("action"), pack);
        }
    }

    /**
     * Method called when a user clicks on the swap button in board.fxml. It checks if the user can do it (his turn),
     * then shows a custom Alert asking the user to pick the deposit he wants to swap (one alert for the first and one
     * for the second)
     * @param event event generated by the press of the button
     */
    public void swap(ActionEvent event){
        if (!gui.getModelView().isActiveTurn()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("It is not your turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        Map<String, String> pack= new HashMap<>();
        List<String> deps= new ArrayList<>(Arrays.asList("small", "mid", "big"));
        if (gui.getModelView().getDeposits(gui.getModelView().getName()).containsKey("sp1res")) deps.add("sp1");
        if (gui.getModelView().getDeposits(gui.getModelView().getName()).containsKey("sp2res")) deps.add("sp2");

        ChoiceDialog<String> choices= new ChoiceDialog<>(deps.get(0), deps);
        choices.initModality(Modality.APPLICATION_MODAL);
        choices.setHeaderText("Swap");
        choices.setContentText("Choose the first deposit");
        Optional<String> result=choices.showAndWait();
        if (result.isPresent()){
            deps.remove(result.get());
            pack.put("source", result.get());
            choices=new ChoiceDialog<>(deps.get(0), deps);
            choices.initModality(Modality.APPLICATION_MODAL);
            choices.setHeaderText("Swap");
            choices.setContentText("Choose the second deposit");
            result=choices.showAndWait();
            result.ifPresent(s -> pack.put("dest", s));
        }

        if (pack.containsKey("source") && pack.containsKey("dest")){
            Alert confirm= new Alert(Alert.AlertType.CONFIRMATION);
            confirm.setHeaderText("Swap");
            confirm.setContentText("First dep: "+pack.get("source")+" ; Second dep: "+pack.get("dest")+". Do you confirm the action?");
            confirm.initModality(Modality.APPLICATION_MODAL);
            Optional<ButtonType> res= confirm.showAndWait();
            if (result.isPresent() && res.get()==ButtonType.OK){
                pack.put("action", "swap");
                pack.put("player", gui.getModelView().getName());
                gui.getListeners().fireUpdates(pack.get("action"), pack);
            }
        }
    }

    /**
     * Method called when a user clicks on the show button in board.fxml. It checks if the user can do it (!soloGame),
     * then shows the user a choiceDialog asking the name of the player he wants to see
     * @param event event generated by the press of the button
     */
    public void show(ActionEvent event){
        //Tramite Alert.CONFIRMATION chiedono nome utente da visualizzare, poi chiama metodo show su ShowController
        if (gui.getModelView().isSoloGame()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("This action is available only for a multiplayer game!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }
        List<String> names=gui.getModelView().getPlayers();
        names.remove(gui.getModelView().getName());
        ChoiceDialog<String> choices= new ChoiceDialog<>(names.get(0), names);
        choices.setHeaderText("Show Player");
        choices.setContentText("Choose the player you want to see");
        choices.initModality(Modality.APPLICATION_MODAL);
        Optional<String> result=choices.showAndWait();
        if (result.isPresent()) {
            ShowController controller=(ShowController) gui.getControllerFromName("show.fxml");
            controller.prepareShow(result.get());
        }
    }

    /**
     * Method called when a user clicks on the endturn button in board.fxml. It checks if the user can do it (his turn and
     * doneMandatory), then sends the action gui's listener(s)
     * @param event event generated by the press of the button
     */
    public void endTurn(ActionEvent event){
        //Chiede conferma fine turno con Alert.CONFIRMATION poi invia pack.
        if (!gui.getModelView().isActiveTurn()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("It is not your turn!");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        if (!gui.getModelView().isDoneMandatory()){
            Alert error= new Alert(Alert.AlertType.ERROR);
            error.setHeaderText("Error! You can't do it!");
            error.setContentText("You must do one action between BUY, MARKET, PRODUCE before ending turn");
            error.initModality(Modality.APPLICATION_MODAL);
            error.showAndWait();
            return;
        }

        Alert confirm= new Alert(Alert.AlertType.CONFIRMATION);
        confirm.setHeaderText("Ending Turn");
        confirm.setContentText("Are you sure you want to end your turn?");
        confirm.initModality(Modality.APPLICATION_MODAL);
        Optional<ButtonType> result= confirm.showAndWait();
        if (result.isPresent() && result.get()==ButtonType.OK){
            Map<String, String> pack= new HashMap<>();
            pack.put("action", "endturn");
            pack.put("player", gui.getModelView().getName());
            gui.getListeners().fireUpdates(pack.get("action"), pack);
        }

    }

    //Metodi set per cambiare le informazioni presenti in schermata?

    /**
     * This method updates the Slots on the personal Board.
     */
    public void updateSlots() {
        Platform.runLater( () -> {
                    Image image;
                    List<int[]> slots = gui.getModelView().getSlots(gui.getModelView().getName());
                    int lv;
                    StringBuilder label = new StringBuilder();
                    for (int slot = 0; slot < slots.size(); slot++) {
                        lv = 0;
                        if (gui.getModelView().getTopId(slots.get(slot)) > 0) {
                            // set image
                            image = new Image("/PNG/cards/dc_" + gui.getModelView().getTopId(slots.get(slot)) + ".png");

                            // set label
                            while (lv < slots.get(slot).length) {
                                if (slots.get(slot)[lv] != 0) {
                                    if (lv != 0) label.append(", ");

                                    label.append("LV").append(lv + 1).append(": ").append(Cards.getColorById(slots.get(slot)[lv]));
                                    lv++;
                                } else break;
                            }
                        }
                        else image = null;

                        switch (slot) {
                            case 0:
                                dev0.setImage(image);
                                slot0.setText(label.toString());
                                break;
                            case 1:
                                dev1.setImage(image);
                                slot1.setText(label.toString());
                                break;
                            case 2:
                                dev2.setImage(image);
                                slot2.setText(label.toString());
                                break;
                        }
                    }
        }
        );
    }

    /**
     * This method updates the Leaders on the personal Board (after activate/discard leader actions).
     */
    public void updateLeader() {
        Platform.runLater( () -> {
            Image image;
            Map<String, String> leaders = gui.getModelView().getLeaders(gui.getModelView().getName());
            for (int i = 0; i < leaders.size() / 2; i++) {
                if (leaders.get("state" + i).equalsIgnoreCase("discarded")) image = null;
                else image = new Image("../PNG/cards/lc_" + leaders.get("leader" + i));

                switch (i) {
                    case 0:
                        if (Integer.parseInt(leaders.get("leader" + i)) >= 7 &&
                                Integer.parseInt(leaders.get("leader" + i)) <= 10 &&
                                leaders.get("state" + i).equalsIgnoreCase("active")) {
                            if (Integer.parseInt(leaders.get("leader" + (i+1))) >= 7 &&
                                    Integer.parseInt(leaders.get("leader" + (i+1))) <= 10 &&
                                    leaders.get("state" + (i+1)).equalsIgnoreCase("active"))
                                sp_leader0.setText("SP2");
                            else sp_leader0.setText("SP1");
                            sp_leader0.setOpacity(1);
                        }
                        sp_leader0.setOpacity(0);
                        leader0.setImage(image);
                        if (leaders.get("state" + i).equalsIgnoreCase("active")) leader0.setOpacity(1);
                        else if (leaders.get("state" + i).equalsIgnoreCase("available")) leader0.setOpacity(0.45);
                        break;
                    case 1:
                        if (Integer.parseInt(leaders.get("leader" + i)) >= 7 &&
                                Integer.parseInt(leaders.get("leader" + i)) <= 10 &&
                                leaders.get("state" + i).equalsIgnoreCase("active")) {
                            if (Integer.parseInt(leaders.get("leader" + (i-1))) >= 7 &&
                                    Integer.parseInt(leaders.get("leader" + (i-1))) <= 10 &&
                                    leaders.get("state" + (i-1)).equalsIgnoreCase("active"))
                                sp_leader1.setText("SP2");
                            else sp_leader1.setText("SP1");
                            sp_leader1.setOpacity(1);
                        }
                        sp_leader1.setOpacity(0);
                        leader1.setImage(image);
                        if (leaders.get("state" + i).equalsIgnoreCase("active")) leader1.setOpacity(1);
                        else if (leaders.get("state" + i).equalsIgnoreCase("available")) leader1.setOpacity(0.45);
                        break;
                }
            }
        });
    }

    /**
     * @see GUIController
     * @param gui the gui to be set
     */
    @Override
    public void setGui(GUI gui) {
        this.gui=gui;
    }
}
